version: 0.0      # can give any version
os: linux
files:
  - source: /         # file is on root dir of github repo
    destination: /home/ubuntu/app         # will be moved to this location of EC2 instance 
hooks:
  BeforeInstall:      # here we will install req dependencies, and clean up 
    - location: deploy/scripts/install_dependencies.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:     # once server ready run the container and server the api
    - location: deploy/scripts/start_docker.sh
      timeout: 300
      runas: ubuntu
      